export const fetchdata = async () => {
    try {
        const options = {
            method: 'GET',
            headers: {
                'X-RapidAPI-Key': 'fdc5b8b18fmshe471f1764ee9198p11ca05jsnb92790e9e348',
                'X-RapidAPI-Host': 'corona-virus-world-and-india-data.p.rapidapi.com'
            }
        };

        const data = await fetch('https://corona-virus-world-and-india-data.p.rapidapi.com/api', options);
        const datajson = await data.json();
        const worldstat = datajson.world_total;
        const modifieddata = {
            confirmed: parseInt(worldstat.total_cases.replace(/,/g, '')),
            deaths: parseInt(worldstat.total_deaths.replace(/,/g, '')),
            recovered: parseInt(worldstat.total_recovered.replace(/,/g, '')),
            lastUpdate: worldstat.statistic_taken_at,
        }

        //console.log(modifieddata);
        return modifieddata;
    } catch (error) {
        console.log("Data not found");
    }
}

export const fetchdailydata=async()=>{
    const data=[
        {
          "dailyconfirmed": "1",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "30 January ",
          "totalconfirmed": "1",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "31 January ",
          "totalconfirmed": "1",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "01 February ",
          "totalconfirmed": "1",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "1",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "02 February ",
          "totalconfirmed": "2",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "1",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "03 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "04 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "05 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "06 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "07 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "08 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "09 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "10 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "11 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "12 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "0"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "1",
          "date": "13 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "1"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "14 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "1"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "15 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "1"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "1",
          "date": "16 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "2"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "17 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "2"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "18 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "2"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "19 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "2"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "1",
          "date": "20 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "21 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "22 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "23 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "24 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "25 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "26 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "27 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "28 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "29 February ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "0",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "01 March ",
          "totalconfirmed": "3",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "2",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "02 March ",
          "totalconfirmed": "5",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "1",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "03 March ",
          "totalconfirmed": "6",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "22",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "04 March ",
          "totalconfirmed": "28",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "2",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "05 March ",
          "totalconfirmed": "30",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "1",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "06 March ",
          "totalconfirmed": "31",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "3",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "07 March ",
          "totalconfirmed": "34",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "5",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "08 March ",
          "totalconfirmed": "39",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "9",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "09 March ",
          "totalconfirmed": "48",
          "totaldeceased": "0",
          "totalrecovered": "3"
        },
        {
          "dailyconfirmed": "15",
          "dailydeceased": "0",
          "dailyrecovered": "1",
          "date": "10 March ",
          "totalconfirmed": "63",
          "totaldeceased": "0",
          "totalrecovered": "4"
        },
        {
          "dailyconfirmed": "7",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "11 March ",
          "totalconfirmed": "70",
          "totaldeceased": "0",
          "totalrecovered": "4"
        },
        {
          "dailyconfirmed": "12",
          "dailydeceased": "1",
          "dailyrecovered": "0",
          "date": "12 March ",
          "totalconfirmed": "82",
          "totaldeceased": "1",
          "totalrecovered": "4"
        },
        {
          "dailyconfirmed": "9",
          "dailydeceased": "0",
          "dailyrecovered": "6",
          "date": "13 March ",
          "totalconfirmed": "91",
          "totaldeceased": "1",
          "totalrecovered": "10"
        },
        {
          "dailyconfirmed": "16",
          "dailydeceased": "1",
          "dailyrecovered": "0",
          "date": "14 March ",
          "totalconfirmed": "107",
          "totaldeceased": "2",
          "totalrecovered": "10"
        },
        {
          "dailyconfirmed": "6",
          "dailydeceased": "0",
          "dailyrecovered": "3",
          "date": "15 March ",
          "totalconfirmed": "113",
          "totaldeceased": "2",
          "totalrecovered": "13"
        },
        {
          "dailyconfirmed": "14",
          "dailydeceased": "0",
          "dailyrecovered": "1",
          "date": "16 March ",
          "totalconfirmed": "127",
          "totaldeceased": "2",
          "totalrecovered": "14"
        },
        {
          "dailyconfirmed": "19",
          "dailydeceased": "1",
          "dailyrecovered": "1",
          "date": "17 March ",
          "totalconfirmed": "146",
          "totaldeceased": "3",
          "totalrecovered": "15"
        },
        {
          "dailyconfirmed": "25",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "18 March ",
          "totalconfirmed": "171",
          "totaldeceased": "3",
          "totalrecovered": "15"
        },
        {
          "dailyconfirmed": "28",
          "dailydeceased": "1",
          "dailyrecovered": "5",
          "date": "19 March ",
          "totalconfirmed": "199",
          "totaldeceased": "4",
          "totalrecovered": "20"
        },
        {
          "dailyconfirmed": "59",
          "dailydeceased": "0",
          "dailyrecovered": "3",
          "date": "20 March ",
          "totalconfirmed": "258",
          "totaldeceased": "4",
          "totalrecovered": "23"
        },
        {
          "dailyconfirmed": "76",
          "dailydeceased": "0",
          "dailyrecovered": "0",
          "date": "21 March ",
          "totalconfirmed": "334",
          "totaldeceased": "4",
          "totalrecovered": "23"
        },
        {
          "dailyconfirmed": "69",
          "dailydeceased": "3",
          "dailyrecovered": "0",
          "date": "22 March ",
          "totalconfirmed": "403",
          "totaldeceased": "7",
          "totalrecovered": "23"
        },
        {
          "dailyconfirmed": "102",
          "dailydeceased": "2",
          "dailyrecovered": "2",
          "date": "23 March ",
          "totalconfirmed": "505",
          "totaldeceased": "9",
          "totalrecovered": "25"
        },
        {
          "dailyconfirmed": "66",
          "dailydeceased": "1",
          "dailyrecovered": "15",
          "date": "24 March ",
          "totalconfirmed": "571",
          "totaldeceased": "10",
          "totalrecovered": "40"
        },
        {
          "dailyconfirmed": "86",
          "dailydeceased": "1",
          "dailyrecovered": "3",
          "date": "25 March ",
          "totalconfirmed": "657",
          "totaldeceased": "11",
          "totalrecovered": "43"
        },
        {
          "dailyconfirmed": "78",
          "dailydeceased": "5",
          "dailyrecovered": "7",
          "date": "26 March ",
          "totalconfirmed": "735",
          "totaldeceased": "16",
          "totalrecovered": "50"
        },
        {
          "dailyconfirmed": "151",
          "dailydeceased": "3",
          "dailyrecovered": "25",
          "date": "27 March ",
          "totalconfirmed": "886",
          "totaldeceased": "19",
          "totalrecovered": "75"
        },
        {
          "dailyconfirmed": "143",
          "dailydeceased": "5",
          "dailyrecovered": "10",
          "date": "28 March ",
          "totalconfirmed": "1029",
          "totaldeceased": "24",
          "totalrecovered": "85"
        },
        {
          "dailyconfirmed": "110",
          "dailydeceased": "3",
          "dailyrecovered": "17",
          "date": "29 March ",
          "totalconfirmed": "1139",
          "totaldeceased": "27",
          "totalrecovered": "102"
        },
        {
          "dailyconfirmed": "208",
          "dailydeceased": "16",
          "dailyrecovered": "35",
          "date": "30 March ",
          "totalconfirmed": "1347",
          "totaldeceased": "43",
          "totalrecovered": "137"
        },
        {
          "dailyconfirmed": "288",
          "dailydeceased": "6",
          "dailyrecovered": "13",
          "date": "31 March ",
          "totalconfirmed": "1635",
          "totaldeceased": "49",
          "totalrecovered": "150"
        },
        {
          "dailyconfirmed": "424",
          "dailydeceased": "7",
          "dailyrecovered": "19",
          "date": "01 April ",
          "totalconfirmed": "2059",
          "totaldeceased": "56",
          "totalrecovered": "169"
        },
        {
          "dailyconfirmed": "486",
          "dailydeceased": "16",
          "dailyrecovered": "22",
          "date": "02 April ",
          "totalconfirmed": "2545",
          "totaldeceased": "72",
          "totalrecovered": "191"
        },
        {
          "dailyconfirmed": "560",
          "dailydeceased": "14",
          "dailyrecovered": "39",
          "date": "03 April ",
          "totalconfirmed": "3105",
          "totaldeceased": "86",
          "totalrecovered": "230"
        },
        {
          "dailyconfirmed": "570",
          "dailydeceased": "13",
          "dailyrecovered": "56",
          "date": "04 April ",
          "totalconfirmed": "3675",
          "totaldeceased": "99",
          "totalrecovered": "286"
        }
      ]
      const mod=data.map((element)=>({
        confirmed:parseInt(element.totalconfirmed.replace(/,/g, '')),
        deaths:parseInt(element.totaldeceased.replace(/,/g, '')),
        recovered:parseInt(element.totalrecovered.replace(/,/g, '')),
        lastUpdate:element.date,
      }))
      //console.log(mod);
      return mod;
}

export const fetchcountry=async(country)=>{
    const data=[
          {
            "country_name": "USA",
            "cases": "521,714",
            "deaths": "20,064",
            "region": "",
            "total_recovered": "28,580",
            "new_deaths": "1,317",
            "new_cases": "18,838",
            "serious_critical": "10,952",
            "active_cases": "473,070",
            "total_cases_per_1m_population": "1,576"
          },
          {
            "country_name": "Spain",
            "cases": "161,852",
            "deaths": "16,353",
            "region": "",
            "total_recovered": "59,109",
            "new_deaths": "272",
            "new_cases": "3,579",
            "serious_critical": "7,371",
            "active_cases": "86,390",
            "total_cases_per_1m_population": "3,462"
          },
          {
            "country_name": "Italy",
            "cases": "152,271",
            "deaths": "19,468",
            "region": "",
            "total_recovered": "32,534",
            "new_deaths": "619",
            "new_cases": "4,694",
            "serious_critical": "3,381",
            "active_cases": "100,269",
            "total_cases_per_1m_population": "2,518"
          },
          {
            "country_name": "France",
            "cases": "129,654",
            "deaths": "13,832",
            "region": "",
            "total_recovered": "26,391",
            "new_deaths": "635",
            "new_cases": "4,785",
            "serious_critical": "6,883",
            "active_cases": "89,431",
            "total_cases_per_1m_population": "1,986"
          },
          {
            "country_name": "Germany",
            "cases": "123,878",
            "deaths": "2,736",
            "region": "",
            "total_recovered": "53,913",
            "new_deaths": "0",
            "new_cases": "1,707",
            "serious_critical": "4,895",
            "active_cases": "67,229",
            "total_cases_per_1m_population": "1,479"
          },
          {
            "country_name": "UK",
            "cases": "78,991",
            "deaths": "9,875",
            "region": "",
            "total_recovered": "344",
            "new_deaths": "917",
            "new_cases": "5,233",
            "serious_critical": "1,559",
            "active_cases": "68,772",
            "total_cases_per_1m_population": "1,164"
          },
          {
            "country_name": "Iran",
            "cases": "70,029",
            "deaths": "4,357",
            "region": "",
            "total_recovered": "41,947",
            "new_deaths": "125",
            "new_cases": "1,837",
            "serious_critical": "3,987",
            "active_cases": "23,725",
            "total_cases_per_1m_population": "834"
          },
          {
            "country_name": "Turkey",
            "cases": "52,167",
            "deaths": "1,101",
            "region": "",
            "total_recovered": "2,965",
            "new_deaths": "95",
            "new_cases": "5,138",
            "serious_critical": "1,626",
            "active_cases": "48,101",
            "total_cases_per_1m_population": "619"
          },
          {
            "country_name": "Belgium",
            "cases": "28,018",
            "deaths": "3,346",
            "region": "",
            "total_recovered": "5,986",
            "new_deaths": "327",
            "new_cases": "1,351",
            "serious_critical": "1,262",
            "active_cases": "18,686",
            "total_cases_per_1m_population": "2,418"
          },
          {
            "country_name": "Switzerland",
            "cases": "25,107",
            "deaths": "1,036",
            "region": "",
            "total_recovered": "11,100",
            "new_deaths": "34",
            "new_cases": "556",
            "serious_critical": "386",
            "active_cases": "12,971",
            "total_cases_per_1m_population": "2,901"
          },
          {
            "country_name": "Netherlands",
            "cases": "24,413",
            "deaths": "2,643",
            "region": "",
            "total_recovered": "250",
            "new_deaths": "132",
            "new_cases": "1,316",
            "serious_critical": "1,384",
            "active_cases": "21,520",
            "total_cases_per_1m_population": "1,425"
          },
          {
            "country_name": "Canada",
            "cases": "22,575",
            "deaths": "600",
            "region": "",
            "total_recovered": "6,013",
            "new_deaths": "31",
            "new_cases": "427",
            "serious_critical": "557",
            "active_cases": "15,962",
            "total_cases_per_1m_population": "598"
          },
          {
            "country_name": "Brazil",
            "cases": "20,022",
            "deaths": "1,075",
            "region": "",
            "total_recovered": "173",
            "new_deaths": "7",
            "new_cases": "233",
            "serious_critical": "296",
            "active_cases": "18,774",
            "total_cases_per_1m_population": "94"
          },
          {
            "country_name": "Portugal",
            "cases": "15,987",
            "deaths": "470",
            "region": "",
            "total_recovered": "266",
            "new_deaths": "35",
            "new_cases": "515",
            "serious_critical": "233",
            "active_cases": "15,251",
            "total_cases_per_1m_population": "1,568"
          },
          {
            "country_name": "Austria",
            "cases": "13,798",
            "deaths": "337",
            "region": "",
            "total_recovered": "6,604",
            "new_deaths": "18",
            "new_cases": "238",
            "serious_critical": "246",
            "active_cases": "6,857",
            "total_cases_per_1m_population": "1,532"
          },
          {
            "country_name": "Russia",
            "cases": "13,584",
            "deaths": "106",
            "region": "",
            "total_recovered": "1,045",
            "new_deaths": "12",
            "new_cases": "1,667",
            "serious_critical": "8",
            "active_cases": "12,433",
            "total_cases_per_1m_population": "93"
          },
          {
            "country_name": "Israel",
            "cases": "10,525",
            "deaths": "96",
            "region": "",
            "total_recovered": "1,258",
            "new_deaths": "1",
            "new_cases": "117",
            "serious_critical": "180",
            "active_cases": "9,171",
            "total_cases_per_1m_population": "1,216"
          },
          {
            "country_name": "S. Korea",
            "cases": "10,480",
            "deaths": "211",
            "region": "",
            "total_recovered": "7,243",
            "new_deaths": "3",
            "new_cases": "30",
            "serious_critical": "55",
            "active_cases": "3,026",
            "total_cases_per_1m_population": "204"
          },
          {
            "country_name": "Sweden",
            "cases": "10,151",
            "deaths": "887",
            "region": "",
            "total_recovered": "381",
            "new_deaths": "17",
            "new_cases": "466",
            "serious_critical": "774",
            "active_cases": "8,883",
            "total_cases_per_1m_population": "1,005"
          },
          {
            "country_name": "India",
            "cases": "8,339",
            "deaths": "288",
            "region": "",
            "total_recovered": "969",
            "new_deaths": "39",
            "new_cases": "739",
            "serious_critical": "0",
            "active_cases": "7,082",
            "total_cases_per_1m_population": "6"
          },
          {
            "country_name": "Ireland",
            "cases": "8,089",
            "deaths": "287",
            "region": "",
            "total_recovered": "25",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "194",
            "active_cases": "7,777",
            "total_cases_per_1m_population": "1,638"
          },
          {
            "country_name": "Ecuador",
            "cases": "7,257",
            "deaths": "315",
            "region": "",
            "total_recovered": "411",
            "new_deaths": "18",
            "new_cases": "96",
            "serious_critical": "184",
            "active_cases": "6,531",
            "total_cases_per_1m_population": "411"
          },
          {
            "country_name": "Chile",
            "cases": "6,927",
            "deaths": "73",
            "region": "",
            "total_recovered": "1,864",
            "new_deaths": "8",
            "new_cases": "426",
            "serious_critical": "383",
            "active_cases": "4,990",
            "total_cases_per_1m_population": "362"
          },
          {
            "country_name": "Peru",
            "cases": "6,848",
            "deaths": "181",
            "region": "",
            "total_recovered": "1,739",
            "new_deaths": "12",
            "new_cases": "951",
            "serious_critical": "142",
            "active_cases": "4,928",
            "total_cases_per_1m_population": "208"
          },
          {
            "country_name": "Norway",
            "cases": "6,403",
            "deaths": "117",
            "region": "",
            "total_recovered": "32",
            "new_deaths": "4",
            "new_cases": "89",
            "serious_critical": "67",
            "active_cases": "6,254",
            "total_cases_per_1m_population": "1,181"
          },
          {
            "country_name": "Poland",
            "cases": "6,356",
            "deaths": "208",
            "region": "",
            "total_recovered": "375",
            "new_deaths": "27",
            "new_cases": "401",
            "serious_critical": "160",
            "active_cases": "5,773",
            "total_cases_per_1m_population": "168"
          },
          {
            "country_name": "Australia",
            "cases": "6,303",
            "deaths": "56",
            "region": "",
            "total_recovered": "3,265",
            "new_deaths": "2",
            "new_cases": "65",
            "serious_critical": "80",
            "active_cases": "2,982",
            "total_cases_per_1m_population": "247"
          },
          {
            "country_name": "Japan",
            "cases": "6,005",
            "deaths": "99",
            "region": "",
            "total_recovered": "762",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "109",
            "active_cases": "5,144",
            "total_cases_per_1m_population": "47"
          },
          {
            "country_name": "Denmark",
            "cases": "5,996",
            "deaths": "260",
            "region": "",
            "total_recovered": "1,955",
            "new_deaths": "13",
            "new_cases": "177",
            "serious_critical": "106",
            "active_cases": "3,781",
            "total_cases_per_1m_population": "1,035"
          },
          {
            "country_name": "Romania",
            "cases": "5,990",
            "deaths": "291",
            "region": "",
            "total_recovered": "758",
            "new_deaths": "21",
            "new_cases": "523",
            "serious_critical": "208",
            "active_cases": "4,941",
            "total_cases_per_1m_population": "311"
          },
          {
            "country_name": "Czechia",
            "cases": "5,831",
            "deaths": "129",
            "region": "",
            "total_recovered": "411",
            "new_deaths": "10",
            "new_cases": "99",
            "serious_critical": "92",
            "active_cases": "5,291",
            "total_cases_per_1m_population": "544"
          },
          {
            "country_name": "Pakistan",
            "cases": "5,011",
            "deaths": "77",
            "region": "",
            "total_recovered": "762",
            "new_deaths": "11",
            "new_cases": "316",
            "serious_critical": "50",
            "active_cases": "4,172",
            "total_cases_per_1m_population": "23"
          },
          {
            "country_name": "Malaysia",
            "cases": "4,530",
            "deaths": "73",
            "region": "",
            "total_recovered": "1,995",
            "new_deaths": "3",
            "new_cases": "184",
            "serious_critical": "72",
            "active_cases": "2,462",
            "total_cases_per_1m_population": "140"
          },
          {
            "country_name": "Philippines",
            "cases": "4,428",
            "deaths": "247",
            "region": "",
            "total_recovered": "157",
            "new_deaths": "26",
            "new_cases": "233",
            "serious_critical": "1",
            "active_cases": "4,024",
            "total_cases_per_1m_population": "40"
          },
          {
            "country_name": "Saudi Arabia",
            "cases": "4,033",
            "deaths": "52",
            "region": "",
            "total_recovered": "720",
            "new_deaths": "5",
            "new_cases": "382",
            "serious_critical": "57",
            "active_cases": "3,261",
            "total_cases_per_1m_population": "116"
          },
          {
            "country_name": "Mexico",
            "cases": "3,844",
            "deaths": "233",
            "region": "",
            "total_recovered": "633",
            "new_deaths": "39",
            "new_cases": "403",
            "serious_critical": "89",
            "active_cases": "2,978",
            "total_cases_per_1m_population": "30"
          },
          {
            "country_name": "Indonesia",
            "cases": "3,842",
            "deaths": "327",
            "region": "",
            "total_recovered": "286",
            "new_deaths": "21",
            "new_cases": "330",
            "serious_critical": "0",
            "active_cases": "3,229",
            "total_cases_per_1m_population": "14"
          },
          {
            "country_name": "UAE",
            "cases": "3,736",
            "deaths": "20",
            "region": "",
            "total_recovered": "588",
            "new_deaths": "4",
            "new_cases": "376",
            "serious_critical": "1",
            "active_cases": "3,128",
            "total_cases_per_1m_population": "378"
          },
          {
            "country_name": "Serbia",
            "cases": "3,380",
            "deaths": "74",
            "region": "",
            "total_recovered": "118",
            "new_deaths": "3",
            "new_cases": "275",
            "serious_critical": "145",
            "active_cases": "3,188",
            "total_cases_per_1m_population": "387"
          },
          {
            "country_name": "Luxembourg",
            "cases": "3,270",
            "deaths": "62",
            "region": "",
            "total_recovered": "500",
            "new_deaths": "8",
            "new_cases": "47",
            "serious_critical": "30",
            "active_cases": "2,708",
            "total_cases_per_1m_population": "5,224"
          },
          {
            "country_name": "Panama",
            "cases": "2,974",
            "deaths": "74",
            "region": "",
            "total_recovered": "17",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "104",
            "active_cases": "2,883",
            "total_cases_per_1m_population": "689"
          },
          {
            "country_name": "Finland",
            "cases": "2,905",
            "deaths": "49",
            "region": "",
            "total_recovered": "300",
            "new_deaths": "1",
            "new_cases": "136",
            "serious_critical": "80",
            "active_cases": "2,556",
            "total_cases_per_1m_population": "524"
          },
          {
            "country_name": "Qatar",
            "cases": "2,728",
            "deaths": "6",
            "region": "",
            "total_recovered": "247",
            "new_deaths": "0",
            "new_cases": "216",
            "serious_critical": "37",
            "active_cases": "2,475",
            "total_cases_per_1m_population": "947"
          },
          {
            "country_name": "Dominican Republic",
            "cases": "2,620",
            "deaths": "126",
            "region": "",
            "total_recovered": "98",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "147",
            "active_cases": "2,396",
            "total_cases_per_1m_population": "242"
          },
          {
            "country_name": "Thailand",
            "cases": "2,518",
            "deaths": "35",
            "region": "",
            "total_recovered": "1,135",
            "new_deaths": "2",
            "new_cases": "45",
            "serious_critical": "61",
            "active_cases": "1,348",
            "total_cases_per_1m_population": "36"
          },
          {
            "country_name": "Ukraine",
            "cases": "2,511",
            "deaths": "73",
            "region": "",
            "total_recovered": "79",
            "new_deaths": "4",
            "new_cases": "308",
            "serious_critical": "45",
            "active_cases": "2,359",
            "total_cases_per_1m_population": "57"
          },
          {
            "country_name": "Colombia",
            "cases": "2,473",
            "deaths": "80",
            "region": "",
            "total_recovered": "197",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "85",
            "active_cases": "2,196",
            "total_cases_per_1m_population": "49"
          },
          {
            "country_name": "Singapore",
            "cases": "2,299",
            "deaths": "8",
            "region": "",
            "total_recovered": "528",
            "new_deaths": "1",
            "new_cases": "191",
            "serious_critical": "31",
            "active_cases": "1,763",
            "total_cases_per_1m_population": "393"
          },
          {
            "country_name": "Belarus",
            "cases": "2,226",
            "deaths": "23",
            "region": "",
            "total_recovered": "172",
            "new_deaths": "4",
            "new_cases": "245",
            "serious_critical": "72",
            "active_cases": "2,031",
            "total_cases_per_1m_population": "236"
          },
          {
            "country_name": "Greece",
            "cases": "2,081",
            "deaths": "93",
            "region": "",
            "total_recovered": "269",
            "new_deaths": "1",
            "new_cases": "70",
            "serious_critical": "75",
            "active_cases": "1,719",
            "total_cases_per_1m_population": "200"
          },
          {
            "country_name": "South Africa",
            "cases": "2,028",
            "deaths": "25",
            "region": "",
            "total_recovered": "410",
            "new_deaths": "1",
            "new_cases": "25",
            "serious_critical": "7",
            "active_cases": "1,593",
            "total_cases_per_1m_population": "34"
          },
          {
            "country_name": "Argentina",
            "cases": "1,975",
            "deaths": "83",
            "region": "",
            "total_recovered": "440",
            "new_deaths": "1",
            "new_cases": "0",
            "serious_critical": "115",
            "active_cases": "1,452",
            "total_cases_per_1m_population": "44"
          },
          {
            "country_name": "Algeria",
            "cases": "1,825",
            "deaths": "275",
            "region": "",
            "total_recovered": "460",
            "new_deaths": "19",
            "new_cases": "64",
            "serious_critical": "46",
            "active_cases": "1,090",
            "total_cases_per_1m_population": "42"
          },
          {
            "country_name": "Egypt",
            "cases": "1,794",
            "deaths": "135",
            "region": "",
            "total_recovered": "384",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1,275",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "Iceland",
            "cases": "1,689",
            "deaths": "7",
            "region": "",
            "total_recovered": "841",
            "new_deaths": "0",
            "new_cases": "14",
            "serious_critical": "11",
            "active_cases": "841",
            "total_cases_per_1m_population": "4,950"
          },
          {
            "country_name": "Moldova",
            "cases": "1,560",
            "deaths": "30",
            "region": "",
            "total_recovered": "75",
            "new_deaths": "1",
            "new_cases": "122",
            "serious_critical": "80",
            "active_cases": "1,455",
            "total_cases_per_1m_population": "387"
          },
          {
            "country_name": "Morocco",
            "cases": "1,545",
            "deaths": "111",
            "region": "",
            "total_recovered": "146",
            "new_deaths": "4",
            "new_cases": "97",
            "serious_critical": "1",
            "active_cases": "1,288",
            "total_cases_per_1m_population": "42"
          },
          {
            "country_name": "Croatia",
            "cases": "1,534",
            "deaths": "21",
            "region": "",
            "total_recovered": "323",
            "new_deaths": "0",
            "new_cases": "39",
            "serious_critical": "32",
            "active_cases": "1,190",
            "total_cases_per_1m_population": "374"
          },
          {
            "country_name": "Iraq",
            "cases": "1,318",
            "deaths": "72",
            "region": "",
            "total_recovered": "601",
            "new_deaths": "2",
            "new_cases": "39",
            "serious_critical": "0",
            "active_cases": "645",
            "total_cases_per_1m_population": "33"
          },
          {
            "country_name": "New Zealand",
            "cases": "1,312",
            "deaths": "4",
            "region": "",
            "total_recovered": "422",
            "new_deaths": "2",
            "new_cases": "29",
            "serious_critical": "5",
            "active_cases": "886",
            "total_cases_per_1m_population": "272"
          },
          {
            "country_name": "Hungary",
            "cases": "1,310",
            "deaths": "85",
            "region": "",
            "total_recovered": "115",
            "new_deaths": "8",
            "new_cases": "120",
            "serious_critical": "17",
            "active_cases": "1,110",
            "total_cases_per_1m_population": "136"
          },
          {
            "country_name": "Estonia",
            "cases": "1,304",
            "deaths": "24",
            "region": "",
            "total_recovered": "93",
            "new_deaths": "0",
            "new_cases": "46",
            "serious_critical": "11",
            "active_cases": "1,187",
            "total_cases_per_1m_population": "983"
          },
          {
            "country_name": "Slovenia",
            "cases": "1,188",
            "deaths": "50",
            "region": "",
            "total_recovered": "148",
            "new_deaths": "5",
            "new_cases": "28",
            "serious_critical": "37",
            "active_cases": "990",
            "total_cases_per_1m_population": "571"
          },
          {
            "country_name": "Kuwait",
            "cases": "1,154",
            "deaths": "1",
            "region": "",
            "total_recovered": "133",
            "new_deaths": "0",
            "new_cases": "161",
            "serious_critical": "27",
            "active_cases": "1,020",
            "total_cases_per_1m_population": "270"
          },
          {
            "country_name": "Azerbaijan",
            "cases": "1,058",
            "deaths": "11",
            "region": "",
            "total_recovered": "200",
            "new_deaths": "1",
            "new_cases": "67",
            "serious_critical": "27",
            "active_cases": "847",
            "total_cases_per_1m_population": "104"
          },
          {
            "country_name": "Lithuania",
            "cases": "1,026",
            "deaths": "23",
            "region": "",
            "total_recovered": "54",
            "new_deaths": "1",
            "new_cases": "27",
            "serious_critical": "14",
            "active_cases": "949",
            "total_cases_per_1m_population": "377"
          },
          {
            "country_name": "Bahrain",
            "cases": "1,016",
            "deaths": "6",
            "region": "",
            "total_recovered": "551",
            "new_deaths": "0",
            "new_cases": "91",
            "serious_critical": "3",
            "active_cases": "459",
            "total_cases_per_1m_population": "597"
          },
          {
            "country_name": "Hong Kong",
            "cases": "1,001",
            "deaths": "4",
            "region": "",
            "total_recovered": "336",
            "new_deaths": "0",
            "new_cases": "11",
            "serious_critical": "14",
            "active_cases": "661",
            "total_cases_per_1m_population": "134"
          },
          {
            "country_name": "Armenia",
            "cases": "977",
            "deaths": "13",
            "region": "",
            "total_recovered": "173",
            "new_deaths": "1",
            "new_cases": "40",
            "serious_critical": "30",
            "active_cases": "791",
            "total_cases_per_1m_population": "330"
          },
          {
            "country_name": "Bosnia and Herzegovina",
            "cases": "935",
            "deaths": "37",
            "region": "",
            "total_recovered": "139",
            "new_deaths": "1",
            "new_cases": "34",
            "serious_critical": "4",
            "active_cases": "759",
            "total_cases_per_1m_population": "285"
          },
          {
            "country_name": "Kazakhstan",
            "cases": "865",
            "deaths": "10",
            "region": "",
            "total_recovered": "81",
            "new_deaths": "0",
            "new_cases": "53",
            "serious_critical": "21",
            "active_cases": "774",
            "total_cases_per_1m_population": "46"
          },
          {
            "country_name": "Cameroon",
            "cases": "820",
            "deaths": "12",
            "region": "",
            "total_recovered": "98",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "710",
            "total_cases_per_1m_population": "31"
          },
          {
            "country_name": "North Macedonia",
            "cases": "760",
            "deaths": "34",
            "region": "",
            "total_recovered": "41",
            "new_deaths": "2",
            "new_cases": "49",
            "serious_critical": "15",
            "active_cases": "685",
            "total_cases_per_1m_population": "365"
          },
          {
            "country_name": "Uzbekistan",
            "cases": "729",
            "deaths": "3",
            "region": "",
            "total_recovered": "42",
            "new_deaths": "0",
            "new_cases": "105",
            "serious_critical": "8",
            "active_cases": "684",
            "total_cases_per_1m_population": "22"
          },
          {
            "country_name": "Slovakia",
            "cases": "728",
            "deaths": "2",
            "region": "",
            "total_recovered": "23",
            "new_deaths": "0",
            "new_cases": "13",
            "serious_critical": "5",
            "active_cases": "703",
            "total_cases_per_1m_population": "133"
          },
          {
            "country_name": "Diamond Princess",
            "cases": "712",
            "deaths": "11",
            "region": "",
            "total_recovered": "619",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "10",
            "active_cases": "82",
            "total_cases_per_1m_population": "0"
          },
          {
            "country_name": "Tunisia",
            "cases": "685",
            "deaths": "28",
            "region": "",
            "total_recovered": "43",
            "new_deaths": "3",
            "new_cases": "14",
            "serious_critical": "85",
            "active_cases": "614",
            "total_cases_per_1m_population": "58"
          },
          {
            "country_name": "Bulgaria",
            "cases": "661",
            "deaths": "28",
            "region": "",
            "total_recovered": "62",
            "new_deaths": "3",
            "new_cases": "26",
            "serious_critical": "32",
            "active_cases": "571",
            "total_cases_per_1m_population": "95"
          },
          {
            "country_name": "Latvia",
            "cases": "630",
            "deaths": "3",
            "region": "",
            "total_recovered": "16",
            "new_deaths": "0",
            "new_cases": "18",
            "serious_critical": "2",
            "active_cases": "611",
            "total_cases_per_1m_population": "334"
          },
          {
            "country_name": "Cuba",
            "cases": "620",
            "deaths": "16",
            "region": "",
            "total_recovered": "77",
            "new_deaths": "1",
            "new_cases": "56",
            "serious_critical": "11",
            "active_cases": "527",
            "total_cases_per_1m_population": "55"
          },
          {
            "country_name": "Lebanon",
            "cases": "619",
            "deaths": "20",
            "region": "",
            "total_recovered": "77",
            "new_deaths": "0",
            "new_cases": "10",
            "serious_critical": "34",
            "active_cases": "522",
            "total_cases_per_1m_population": "91"
          },
          {
            "country_name": "Cyprus",
            "cases": "616",
            "deaths": "10",
            "region": "",
            "total_recovered": "61",
            "new_deaths": "0",
            "new_cases": "21",
            "serious_critical": "8",
            "active_cases": "545",
            "total_cases_per_1m_population": "510"
          },
          {
            "country_name": "Andorra",
            "cases": "601",
            "deaths": "26",
            "region": "",
            "total_recovered": "71",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "17",
            "active_cases": "504",
            "total_cases_per_1m_population": "7,778"
          },
          {
            "country_name": "Costa Rica",
            "cases": "558",
            "deaths": "3",
            "region": "",
            "total_recovered": "42",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "13",
            "active_cases": "513",
            "total_cases_per_1m_population": "110"
          },
          {
            "country_name": "Afghanistan",
            "cases": "555",
            "deaths": "18",
            "region": "",
            "total_recovered": "32",
            "new_deaths": "3",
            "new_cases": "34",
            "serious_critical": "0",
            "active_cases": "505",
            "total_cases_per_1m_population": "14"
          },
          {
            "country_name": "Oman",
            "cases": "546",
            "deaths": "3",
            "region": "",
            "total_recovered": "109",
            "new_deaths": "0",
            "new_cases": "62",
            "serious_critical": "3",
            "active_cases": "434",
            "total_cases_per_1m_population": "107"
          },
          {
            "country_name": "Uruguay",
            "cases": "494",
            "deaths": "7",
            "region": "",
            "total_recovered": "214",
            "new_deaths": "0",
            "new_cases": "21",
            "serious_critical": "15",
            "active_cases": "273",
            "total_cases_per_1m_population": "142"
          },
          {
            "country_name": "Bangladesh",
            "cases": "482",
            "deaths": "30",
            "region": "",
            "total_recovered": "36",
            "new_deaths": "3",
            "new_cases": "58",
            "serious_critical": "1",
            "active_cases": "416",
            "total_cases_per_1m_population": "3"
          },
          {
            "country_name": "Ivory Coast",
            "cases": "480",
            "deaths": "3",
            "region": "",
            "total_recovered": "54",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "423",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "Burkina Faso",
            "cases": "448",
            "deaths": "26",
            "region": "",
            "total_recovered": "149",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "273",
            "total_cases_per_1m_population": "21"
          },
          {
            "country_name": "Niger",
            "cases": "438",
            "deaths": "11",
            "region": "",
            "total_recovered": "41",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "386",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "Albania",
            "cases": "433",
            "deaths": "23",
            "region": "",
            "total_recovered": "197",
            "new_deaths": "0",
            "new_cases": "17",
            "serious_critical": "7",
            "active_cases": "213",
            "total_cases_per_1m_population": "150"
          },
          {
            "country_name": "Ghana",
            "cases": "408",
            "deaths": "8",
            "region": "",
            "total_recovered": "4",
            "new_deaths": "2",
            "new_cases": "30",
            "serious_critical": "2",
            "active_cases": "396",
            "total_cases_per_1m_population": "13"
          },
          {
            "country_name": "Channel Islands",
            "cases": "398",
            "deaths": "9",
            "region": "",
            "total_recovered": "40",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "349",
            "total_cases_per_1m_population": "2,289"
          },
          {
            "country_name": "Honduras",
            "cases": "392",
            "deaths": "24",
            "region": "",
            "total_recovered": "7",
            "new_deaths": "1",
            "new_cases": "10",
            "serious_critical": "10",
            "active_cases": "361",
            "total_cases_per_1m_population": "40"
          },
          {
            "country_name": "Réunion",
            "cases": "388",
            "deaths": "0",
            "region": "",
            "total_recovered": "40",
            "new_deaths": "0",
            "new_cases": "6",
            "serious_critical": "3",
            "active_cases": "348",
            "total_cases_per_1m_population": "433"
          },
          {
            "country_name": "Taiwan",
            "cases": "385",
            "deaths": "6",
            "region": "",
            "total_recovered": "99",
            "new_deaths": "0",
            "new_cases": "3",
            "serious_critical": "0",
            "active_cases": "280",
            "total_cases_per_1m_population": "16"
          },
          {
            "country_name": "Jordan",
            "cases": "381",
            "deaths": "7",
            "region": "",
            "total_recovered": "177",
            "new_deaths": "0",
            "new_cases": "9",
            "serious_critical": "5",
            "active_cases": "197",
            "total_cases_per_1m_population": "37"
          },
          {
            "country_name": "Malta",
            "cases": "370",
            "deaths": "3",
            "region": "",
            "total_recovered": "16",
            "new_deaths": "1",
            "new_cases": "20",
            "serious_critical": "4",
            "active_cases": "351",
            "total_cases_per_1m_population": "838"
          },
          {
            "country_name": "San Marino",
            "cases": "356",
            "deaths": "35",
            "region": "",
            "total_recovered": "53",
            "new_deaths": "1",
            "new_cases": "12",
            "serious_critical": "14",
            "active_cases": "268",
            "total_cases_per_1m_population": "10,492"
          },
          {
            "country_name": "Kyrgyzstan",
            "cases": "339",
            "deaths": "5",
            "region": "",
            "total_recovered": "44",
            "new_deaths": "0",
            "new_cases": "41",
            "serious_critical": "5",
            "active_cases": "290",
            "total_cases_per_1m_population": "52"
          },
          {
            "country_name": "Mauritius",
            "cases": "319",
            "deaths": "9",
            "region": "",
            "total_recovered": "28",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "3",
            "active_cases": "282",
            "total_cases_per_1m_population": "251"
          },
          {
            "country_name": "Nigeria",
            "cases": "305",
            "deaths": "7",
            "region": "",
            "total_recovered": "58",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "2",
            "active_cases": "240",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "Senegal",
            "cases": "278",
            "deaths": "2",
            "region": "",
            "total_recovered": "152",
            "new_deaths": "0",
            "new_cases": "13",
            "serious_critical": "1",
            "active_cases": "124",
            "total_cases_per_1m_population": "17"
          },
          {
            "country_name": "Bolivia",
            "cases": "275",
            "deaths": "20",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "1",
            "new_cases": "7",
            "serious_critical": "3",
            "active_cases": "253",
            "total_cases_per_1m_population": "24"
          },
          {
            "country_name": "Palestine",
            "cases": "268",
            "deaths": "2",
            "region": "",
            "total_recovered": "57",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "0",
            "active_cases": "209",
            "total_cases_per_1m_population": "53"
          },
          {
            "country_name": "Montenegro",
            "cases": "263",
            "deaths": "2",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "6",
            "serious_critical": "7",
            "active_cases": "256",
            "total_cases_per_1m_population": "419"
          },
          {
            "country_name": "Vietnam",
            "cases": "258",
            "deaths": "0",
            "region": "",
            "total_recovered": "144",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "8",
            "active_cases": "114",
            "total_cases_per_1m_population": "3"
          },
          {
            "country_name": "Georgia",
            "cases": "242",
            "deaths": "3",
            "region": "",
            "total_recovered": "60",
            "new_deaths": "0",
            "new_cases": "8",
            "serious_critical": "6",
            "active_cases": "179",
            "total_cases_per_1m_population": "61"
          },
          {
            "country_name": "Isle of Man",
            "cases": "226",
            "deaths": "1",
            "region": "",
            "total_recovered": "112",
            "new_deaths": "0",
            "new_cases": "25",
            "serious_critical": "11",
            "active_cases": "113",
            "total_cases_per_1m_population": "2,658"
          },
          {
            "country_name": "DRC",
            "cases": "223",
            "deaths": "20",
            "region": "",
            "total_recovered": "16",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "187",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "Guinea",
            "cases": "212",
            "deaths": "0",
            "region": "",
            "total_recovered": "15",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "197",
            "total_cases_per_1m_population": "16"
          },
          {
            "country_name": "Sri Lanka",
            "cases": "198",
            "deaths": "7",
            "region": "",
            "total_recovered": "54",
            "new_deaths": "0",
            "new_cases": "8",
            "serious_critical": "5",
            "active_cases": "137",
            "total_cases_per_1m_population": "9"
          },
          {
            "country_name": "Mayotte",
            "cases": "196",
            "deaths": "3",
            "region": "",
            "total_recovered": "59",
            "new_deaths": "1",
            "new_cases": "5",
            "serious_critical": "3",
            "active_cases": "134",
            "total_cases_per_1m_population": "718"
          },
          {
            "country_name": "Kenya",
            "cases": "191",
            "deaths": "7",
            "region": "",
            "total_recovered": "24",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "2",
            "active_cases": "160",
            "total_cases_per_1m_population": "4"
          },
          {
            "country_name": "Djibouti",
            "cases": "187",
            "deaths": "2",
            "region": "",
            "total_recovered": "36",
            "new_deaths": "1",
            "new_cases": "37",
            "serious_critical": "0",
            "active_cases": "149",
            "total_cases_per_1m_population": "189"
          },
          {
            "country_name": "Faeroe Islands",
            "cases": "184",
            "deaths": "0",
            "region": "",
            "total_recovered": "145",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "39",
            "total_cases_per_1m_population": "3,766"
          },
          {
            "country_name": "Venezuela",
            "cases": "175",
            "deaths": "9",
            "region": "",
            "total_recovered": "84",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "6",
            "active_cases": "82",
            "total_cases_per_1m_population": "6"
          },
          {
            "country_name": "Martinique",
            "cases": "155",
            "deaths": "6",
            "region": "",
            "total_recovered": "50",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "19",
            "active_cases": "99",
            "total_cases_per_1m_population": "413"
          },
          {
            "country_name": "Guadeloupe",
            "cases": "143",
            "deaths": "8",
            "region": "",
            "total_recovered": "67",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "13",
            "active_cases": "68",
            "total_cases_per_1m_population": "357"
          },
          {
            "country_name": "Guatemala",
            "cases": "137",
            "deaths": "3",
            "region": "",
            "total_recovered": "19",
            "new_deaths": "0",
            "new_cases": "11",
            "serious_critical": "3",
            "active_cases": "115",
            "total_cases_per_1m_population": "8"
          },
          {
            "country_name": "Brunei",
            "cases": "136",
            "deaths": "1",
            "region": "",
            "total_recovered": "104",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "2",
            "active_cases": "31",
            "total_cases_per_1m_population": "311"
          },
          {
            "country_name": "Paraguay",
            "cases": "133",
            "deaths": "6",
            "region": "",
            "total_recovered": "18",
            "new_deaths": "0",
            "new_cases": "4",
            "serious_critical": "1",
            "active_cases": "109",
            "total_cases_per_1m_population": "19"
          },
          {
            "country_name": "Gibraltar",
            "cases": "129",
            "deaths": "0",
            "region": "",
            "total_recovered": "84",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "1",
            "active_cases": "45",
            "total_cases_per_1m_population": "3,829"
          },
          {
            "country_name": "Cambodia",
            "cases": "120",
            "deaths": "0",
            "region": "",
            "total_recovered": "75",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "1",
            "active_cases": "45",
            "total_cases_per_1m_population": "7"
          },
          {
            "country_name": "El Salvador",
            "cases": "118",
            "deaths": "6",
            "region": "",
            "total_recovered": "19",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "4",
            "active_cases": "93",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "Rwanda",
            "cases": "118",
            "deaths": "0",
            "region": "",
            "total_recovered": "18",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "100",
            "total_cases_per_1m_population": "9"
          },
          {
            "country_name": "Trinidad and Tobago",
            "cases": "109",
            "deaths": "8",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "98",
            "total_cases_per_1m_population": "78"
          },
          {
            "country_name": "Madagascar",
            "cases": "102",
            "deaths": "0",
            "region": "",
            "total_recovered": "11",
            "new_deaths": "0",
            "new_cases": "9",
            "serious_critical": "1",
            "active_cases": "91",
            "total_cases_per_1m_population": "4"
          },
          {
            "country_name": "Monaco",
            "cases": "92",
            "deaths": "1",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "4",
            "active_cases": "86",
            "total_cases_per_1m_population": "2,344"
          },
          {
            "country_name": "Aruba",
            "cases": "92",
            "deaths": "0",
            "region": "",
            "total_recovered": "29",
            "new_deaths": "0",
            "new_cases": "6",
            "serious_critical": "0",
            "active_cases": "63",
            "total_cases_per_1m_population": "862"
          },
          {
            "country_name": "Mali",
            "cases": "87",
            "deaths": "7",
            "region": "",
            "total_recovered": "22",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "58",
            "total_cases_per_1m_population": "4"
          },
          {
            "country_name": "French Guiana",
            "cases": "83",
            "deaths": "0",
            "region": "",
            "total_recovered": "43",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "40",
            "total_cases_per_1m_population": "278"
          },
          {
            "country_name": "Liechtenstein",
            "cases": "79",
            "deaths": "1",
            "region": "",
            "total_recovered": "55",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "23",
            "total_cases_per_1m_population": "2,072"
          },
          {
            "country_name": "Togo",
            "cases": "76",
            "deaths": "3",
            "region": "",
            "total_recovered": "25",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "48",
            "total_cases_per_1m_population": "9"
          },
          {
            "country_name": "Ethiopia",
            "cases": "69",
            "deaths": "3",
            "region": "",
            "total_recovered": "10",
            "new_deaths": "0",
            "new_cases": "4",
            "serious_critical": "0",
            "active_cases": "56",
            "total_cases_per_1m_population": "0.6"
          },
          {
            "country_name": "Barbados",
            "cases": "67",
            "deaths": "4",
            "region": "",
            "total_recovered": "11",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "4",
            "active_cases": "52",
            "total_cases_per_1m_population": "233"
          },
          {
            "country_name": "Jamaica",
            "cases": "65",
            "deaths": "4",
            "region": "",
            "total_recovered": "13",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "48",
            "total_cases_per_1m_population": "22"
          },
          {
            "country_name": "Congo",
            "cases": "60",
            "deaths": "5",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "50",
            "total_cases_per_1m_population": "11"
          },
          {
            "country_name": "Uganda",
            "cases": "53",
            "deaths": "0",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "50",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "French Polynesia",
            "cases": "51",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "51",
            "total_cases_per_1m_population": "182"
          },
          {
            "country_name": "Sint Maarten",
            "cases": "50",
            "deaths": "8",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "2",
            "active_cases": "39",
            "total_cases_per_1m_population": "1,166"
          },
          {
            "country_name": "Liberia",
            "cases": "48",
            "deaths": "5",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "11",
            "serious_critical": "0",
            "active_cases": "40",
            "total_cases_per_1m_population": "9"
          },
          {
            "country_name": "Bermuda",
            "cases": "48",
            "deaths": "4",
            "region": "",
            "total_recovered": "25",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "2",
            "active_cases": "19",
            "total_cases_per_1m_population": "771"
          },
          {
            "country_name": "Gabon",
            "cases": "46",
            "deaths": "1",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "44",
            "total_cases_per_1m_population": "21"
          },
          {
            "country_name": "Cayman Islands",
            "cases": "45",
            "deaths": "1",
            "region": "",
            "total_recovered": "6",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "38",
            "total_cases_per_1m_population": "685"
          },
          {
            "country_name": "Macao",
            "cases": "45",
            "deaths": "0",
            "region": "",
            "total_recovered": "10",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "35",
            "total_cases_per_1m_population": "69"
          },
          {
            "country_name": "Bahamas",
            "cases": "42",
            "deaths": "8",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "29",
            "total_cases_per_1m_population": "107"
          },
          {
            "country_name": "Guyana",
            "cases": "40",
            "deaths": "6",
            "region": "",
            "total_recovered": "8",
            "new_deaths": "0",
            "new_cases": "3",
            "serious_critical": "3",
            "active_cases": "26",
            "total_cases_per_1m_population": "51"
          },
          {
            "country_name": "Zambia",
            "cases": "40",
            "deaths": "2",
            "region": "",
            "total_recovered": "28",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "10",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "Guinea-Bissau",
            "cases": "38",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "38",
            "total_cases_per_1m_population": "19"
          },
          {
            "country_name": "Benin",
            "cases": "35",
            "deaths": "1",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "29",
            "total_cases_per_1m_population": "3"
          },
          {
            "country_name": "Eritrea",
            "cases": "34",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "34",
            "total_cases_per_1m_population": "10"
          },
          {
            "country_name": "Tanzania",
            "cases": "32",
            "deaths": "3",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "24",
            "total_cases_per_1m_population": "0.5"
          },
          {
            "country_name": "Saint Martin",
            "cases": "32",
            "deaths": "2",
            "region": "",
            "total_recovered": "11",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "5",
            "active_cases": "19",
            "total_cases_per_1m_population": "828"
          },
          {
            "country_name": "Myanmar",
            "cases": "31",
            "deaths": "3",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "4",
            "serious_critical": "0",
            "active_cases": "26",
            "total_cases_per_1m_population": "0.6"
          },
          {
            "country_name": "Haiti",
            "cases": "31",
            "deaths": "2",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "29",
            "total_cases_per_1m_population": "3"
          },
          {
            "country_name": "Syria",
            "cases": "25",
            "deaths": "5",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "3",
            "new_cases": "6",
            "serious_critical": "0",
            "active_cases": "15",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "Libya",
            "cases": "24",
            "deaths": "1",
            "region": "",
            "total_recovered": "8",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "15",
            "total_cases_per_1m_population": "3"
          },
          {
            "country_name": "Antigua and Barbuda",
            "cases": "21",
            "deaths": "2",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "19",
            "total_cases_per_1m_population": "214"
          },
          {
            "country_name": "Somalia",
            "cases": "21",
            "deaths": "1",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "19",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "Mozambique",
            "cases": "20",
            "deaths": "0",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "18",
            "total_cases_per_1m_population": "0.6"
          },
          {
            "country_name": "Angola",
            "cases": "19",
            "deaths": "2",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "15",
            "total_cases_per_1m_population": "0.6"
          },
          {
            "country_name": "Sudan",
            "cases": "19",
            "deaths": "2",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "15",
            "total_cases_per_1m_population": "0.4"
          },
          {
            "country_name": "Maldives",
            "cases": "19",
            "deaths": "0",
            "region": "",
            "total_recovered": "13",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "6",
            "total_cases_per_1m_population": "35"
          },
          {
            "country_name": "Equatorial Guinea",
            "cases": "18",
            "deaths": "0",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "15",
            "total_cases_per_1m_population": "13"
          },
          {
            "country_name": "Laos",
            "cases": "18",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "18",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "New Caledonia",
            "cases": "18",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "17",
            "total_cases_per_1m_population": "63"
          },
          {
            "country_name": "Dominica",
            "cases": "16",
            "deaths": "0",
            "region": "",
            "total_recovered": "5",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "11",
            "total_cases_per_1m_population": "222"
          },
          {
            "country_name": "Fiji",
            "cases": "16",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "16",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "Mongolia",
            "cases": "16",
            "deaths": "0",
            "region": "",
            "total_recovered": "4",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "12",
            "total_cases_per_1m_population": "5"
          },
          {
            "country_name": "Namibia",
            "cases": "16",
            "deaths": "0",
            "region": "",
            "total_recovered": "3",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "13",
            "total_cases_per_1m_population": "6"
          },
          {
            "country_name": "Saint Lucia",
            "cases": "15",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "14",
            "total_cases_per_1m_population": "82"
          },
          {
            "country_name": "Curaçao",
            "cases": "14",
            "deaths": "1",
            "region": "",
            "total_recovered": "7",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "6",
            "total_cases_per_1m_population": "85"
          },
          {
            "country_name": "Grenada",
            "cases": "14",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "2",
            "active_cases": "14",
            "total_cases_per_1m_population": "124"
          },
          {
            "country_name": "Zimbabwe",
            "cases": "13",
            "deaths": "3",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "10",
            "total_cases_per_1m_population": "0.9"
          },
          {
            "country_name": "Belize",
            "cases": "13",
            "deaths": "2",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "3",
            "serious_critical": "1",
            "active_cases": "11",
            "total_cases_per_1m_population": "33"
          },
          {
            "country_name": "Botswana",
            "cases": "13",
            "deaths": "1",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "12",
            "total_cases_per_1m_population": "6"
          },
          {
            "country_name": "Malawi",
            "cases": "12",
            "deaths": "2",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "1",
            "new_cases": "3",
            "serious_critical": "1",
            "active_cases": "10",
            "total_cases_per_1m_population": "0.6"
          },
          {
            "country_name": "Saint Kitts and Nevis",
            "cases": "12",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "12",
            "total_cases_per_1m_population": "226"
          },
          {
            "country_name": "St. Vincent Grenadines",
            "cases": "12",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "11",
            "total_cases_per_1m_population": "108"
          },
          {
            "country_name": "Eswatini",
            "cases": "12",
            "deaths": "0",
            "region": "",
            "total_recovered": "7",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "5",
            "total_cases_per_1m_population": "10"
          },
          {
            "country_name": "Chad",
            "cases": "11",
            "deaths": "0",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "9",
            "total_cases_per_1m_population": "0.7"
          },
          {
            "country_name": "Greenland",
            "cases": "11",
            "deaths": "0",
            "region": "",
            "total_recovered": "11",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "0",
            "total_cases_per_1m_population": "194"
          },
          {
            "country_name": "Seychelles",
            "cases": "11",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "11",
            "total_cases_per_1m_population": "112"
          },
          {
            "country_name": "Suriname",
            "cases": "10",
            "deaths": "1",
            "region": "",
            "total_recovered": "4",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "5",
            "total_cases_per_1m_population": "17"
          },
          {
            "country_name": "MS Zaandam",
            "cases": "9",
            "deaths": "2",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "7",
            "total_cases_per_1m_population": "0"
          },
          {
            "country_name": "Nepal",
            "cases": "9",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "8",
            "total_cases_per_1m_population": "0.3"
          },
          {
            "country_name": "Montserrat",
            "cases": "9",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "1",
            "active_cases": "9",
            "total_cases_per_1m_population": "1,803"
          },
          {
            "country_name": "Cabo Verde",
            "cases": "8",
            "deaths": "1",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "0",
            "active_cases": "6",
            "total_cases_per_1m_population": "14"
          },
          {
            "country_name": "Nicaragua",
            "cases": "8",
            "deaths": "1",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "1",
            "serious_critical": "0",
            "active_cases": "7",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "Turks and Caicos",
            "cases": "8",
            "deaths": "1",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "7",
            "total_cases_per_1m_population": "207"
          },
          {
            "country_name": "CAR",
            "cases": "8",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "8",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "Vatican City",
            "cases": "8",
            "deaths": "0",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "6",
            "total_cases_per_1m_population": "9,988"
          },
          {
            "country_name": "Sierra Leone",
            "cases": "8",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "8",
            "total_cases_per_1m_population": "1"
          },
          {
            "country_name": "Mauritania",
            "cases": "7",
            "deaths": "1",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "4",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "St. Barth",
            "cases": "6",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "5",
            "total_cases_per_1m_population": "607"
          },
          {
            "country_name": "Bhutan",
            "cases": "5",
            "deaths": "0",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "3",
            "total_cases_per_1m_population": "6"
          },
          {
            "country_name": "Burundi",
            "cases": "5",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "2",
            "serious_critical": "0",
            "active_cases": "5",
            "total_cases_per_1m_population": "0.4"
          },
          {
            "country_name": "Falkland Islands",
            "cases": "5",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "4",
            "total_cases_per_1m_population": "1,437"
          },
          {
            "country_name": "Gambia",
            "cases": "4",
            "deaths": "1",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "Sao Tome and Principe",
            "cases": "4",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "4",
            "total_cases_per_1m_population": "18"
          },
          {
            "country_name": "South Sudan",
            "cases": "4",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "4",
            "total_cases_per_1m_population": "0.4"
          },
          {
            "country_name": "Western Sahara",
            "cases": "4",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "4",
            "total_cases_per_1m_population": "7"
          },
          {
            "country_name": "Anguilla",
            "cases": "3",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "3",
            "total_cases_per_1m_population": "200"
          },
          {
            "country_name": "British Virgin Islands",
            "cases": "3",
            "deaths": "0",
            "region": "",
            "total_recovered": "2",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1",
            "total_cases_per_1m_population": "99"
          },
          {
            "country_name": "Caribbean Netherlands",
            "cases": "2",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "2",
            "total_cases_per_1m_population": "76"
          },
          {
            "country_name": "Papua New Guinea",
            "cases": "2",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "2",
            "total_cases_per_1m_population": "0.2"
          },
          {
            "country_name": "Timor-Leste",
            "cases": "2",
            "deaths": "0",
            "region": "",
            "total_recovered": "1",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1",
            "total_cases_per_1m_population": "2"
          },
          {
            "country_name": "Saint Pierre Miquelon",
            "cases": "1",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1",
            "total_cases_per_1m_population": "173"
          },
          {
            "country_name": "Yemen",
            "cases": "1",
            "deaths": "0",
            "region": "",
            "total_recovered": "0",
            "new_deaths": "0",
            "new_cases": "0",
            "serious_critical": "0",
            "active_cases": "1",
            "total_cases_per_1m_population": "0.03"
          },
          {
            "country_name": "China",
            "cases": "81,953",
            "deaths": "3,339",
            "region": "",
            "total_recovered": "77,525",
            "new_deaths": "3",
            "new_cases": "46",
            "serious_critical": "141",
            "active_cases": "1,089",
            "total_cases_per_1m_population": "57"
          }
        ]
    if(country){
        for (let index = 0; index < data.length; index++) {
            const element = data[index];
            if(element.country_name===country){
                const mod={
                    confirmed:parseInt(element.cases.replace(/,/g, '')),
                    deaths:parseInt(element.deaths.replace(/,/g, '')),
                    recovered:parseInt(element.total_recovered.replace(/,/g, '')),
                    lastUpdate:'2020-04-11 17:59:07',
                  }
                  return mod;
            }
        }
    }
    const mod=data.map((countrydata)=>({
        country:countrydata.country_name,
    }));
    //console.log(mod);
    return mod;
}